[project]
name = "sparv-sbx-word-prediction-workspace"
dependencies = []
requires-python = ">=3.9"
version = "0.0.0"


[tool.uv.workspace]
members = ["word-prediction-kb-bert"]

[dependency-groups]
dev = [
    "pytest-cov>=6.0.0",
    "pytest>=8.3.3",
    "ruff>=0.7.4",
    "mypy>=1.13.0",
]
