[project]
name = "sparv-bert-neighbour-plugin"
version = "0.1.0"
description = "A sparv plugin for computing word neighbours using a BERT model."
authors = [
    { name = "Kristoffer Andersson", email = "kristoffer.andersson@gu.se" },
]
dependencies = [
    "sparv-pipeline >=5.2.0",
    "transformers>=4.34.1",
    "tabulate>=0.9.0",
]
readme = "README.md"
requires-python = ">= 3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.entry-points."sparv.plugin"]
sparv_bert_neighbour = "sparv_bert_neighbour"

[tool.rye]
managed = true
dev-dependencies = ["pytest>=7.4.2", "black>=23.10.1"]

[tool.hatch.build.targets.sdist]
exclude = ["/.github", "/docs"]

[tool.hatch.build.targets.wheel]
packages = ["src/sparv_bert_neighbour"]

[tool.hatch.metadata]
allow-direct-references = true
