[project]
name = "sparv-sbx-word-prediction-workspace"
dependencies = []
requires-python = ">=3.9"
version = "0.0.0"


[tool.uv.workspace]
members = ["word-prediction-kb-bert"]

[dependency-groups]
dev = ["pytest>=8.3.3"]
