[project]
name = "sparv-bert-mask-plugin"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Kristoffer Andersson", email = "kristoffer.andersson@gu.se" },
]
dependencies = [
    "sparv-pipeline @ git+https://github.com/kod-kristoff/sparv-pipeline.git@deps-update",
    "transformers>=4.34.1",
    "tabulate>=0.9.0",
    "tensorflow>=2.13.1",
]
readme = "README.md"
requires-python = ">= 3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.entry-points."sparv.plugin"]
sparv_bert_mask = "sparv_bert_mask"

[tool.rye]
managed = true
dev-dependencies = ["pytest>=7.4.2", "black>=23.10.1"]

[tool.hatch.build.targets.sdist]
exclude = ["/.github", "/docs"]

[tool.hatch.build.targets.wheel]
packages = ["src/sparv_bert_mask"]

[tool.hatch.metadata]
allow-direct-references = true
