metadata:
    id: hello-bert-mask
    language: swe

import:
    importer: text_import:parse

export:
    annotations:
        - <sentence>
        - <token:word>
        - <token>:stanza.pos
        - <token>:bert_neighbour.transformer-neighbour

sparv:
    compression: none
